# Site settings
title: Sofía Belén López
email: sofiabelenlopez00@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://sofiabelen.github.io/"
github_username:  sofiabelen

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-compose

sass:
    sass_dir: _sass

paginate: 6
paginate_path: /page:num/

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"

permalink: /:categories/:title:output_ext

markdown: CommonMarkGhPages

timezone: Europe/Moscow

jekyll_compose:
  auto_open: true
  default_front_matter:
    posts:
      last_modified_at: 
      permalink: 
      description:
      published: true
      sitemap: true
      excerpt_separator: <!--more-->
      categories:
      tags:
      preview:
